# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/zhangtooru/Desktop/TProxy/main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.RequestFrame = QtWidgets.QFrame(self.centralWidget)
        self.RequestFrame.setGeometry(QtCore.QRect(10, 60, 781, 111))
        self.RequestFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.RequestFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.RequestFrame.setObjectName("RequestFrame")
        self.methodSelect = QtWidgets.QComboBox(self.RequestFrame)
        self.methodSelect.setGeometry(QtCore.QRect(90, 50, 79, 22))
        self.methodSelect.setObjectName("methodSelect")
        self.methodSelect.addItem("")
        self.methodSelect.addItem("")
        self.methodSelect.addItem("")
        self.methodSelect.addItem("")
        self.methodSelect.addItem("")
        self.urlText = QtWidgets.QLineEdit(self.RequestFrame)
        self.urlText.setGeometry(QtCore.QRect(270, 50, 161, 22))
        self.urlText.setObjectName("urlText")
        self.reqruleSelect = QtWidgets.QComboBox(self.RequestFrame)
        self.reqruleSelect.setGeometry(QtCore.QRect(520, 50, 79, 22))
        self.reqruleSelect.setObjectName("reqruleSelect")
        self.reqruleSelect.addItem("")
        self.reqruleSelect.addItem("")
        self.reqruleButton = QtWidgets.QPushButton(self.RequestFrame)
        self.reqruleButton.setGeometry(QtCore.QRect(670, 50, 80, 31))
        self.reqruleButton.setObjectName("reqruleButton")
        self.requestTitle = QtWidgets.QLabel(self.RequestFrame)
        self.requestTitle.setGeometry(QtCore.QRect(20, 10, 91, 21))
        self.requestTitle.setObjectName("requestTitle")
        self.methodLabel = QtWidgets.QLabel(self.RequestFrame)
        self.methodLabel.setGeometry(QtCore.QRect(30, 50, 91, 21))
        self.methodLabel.setObjectName("methodLabel")
        self.urlLabel = QtWidgets.QLabel(self.RequestFrame)
        self.urlLabel.setGeometry(QtCore.QRect(240, 50, 91, 21))
        self.urlLabel.setObjectName("urlLabel")
        self.reqruleLable = QtWidgets.QLabel(self.RequestFrame)
        self.reqruleLable.setGeometry(QtCore.QRect(480, 50, 91, 21))
        self.reqruleLable.setObjectName("reqruleLable")
        self.responseFrame = QtWidgets.QFrame(self.centralWidget)
        self.responseFrame.setGeometry(QtCore.QRect(10, 190, 781, 121))
        self.responseFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.responseFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.responseFrame.setObjectName("responseFrame")
        self.responseTitle = QtWidgets.QLabel(self.responseFrame)
        self.responseTitle.setGeometry(QtCore.QRect(20, 20, 91, 21))
        self.responseTitle.setObjectName("responseTitle")
        self.typeLabel = QtWidgets.QLabel(self.responseFrame)
        self.typeLabel.setGeometry(QtCore.QRect(20, 60, 91, 21))
        self.typeLabel.setObjectName("typeLabel")
        self.typeSelect = QtWidgets.QComboBox(self.responseFrame)
        self.typeSelect.setGeometry(QtCore.QRect(70, 60, 79, 22))
        self.typeSelect.setObjectName("typeSelect")
        self.typeSelect.addItem("")
        self.typeSelect.addItem("")
        self.typeSelect.addItem("")
        self.ipLabel = QtWidgets.QLabel(self.responseFrame)
        self.ipLabel.setGeometry(QtCore.QRect(240, 60, 91, 21))
        self.ipLabel.setObjectName("ipLabel")
        self.ipText = QtWidgets.QLineEdit(self.responseFrame)
        self.ipText.setGeometry(QtCore.QRect(270, 60, 161, 22))
        self.ipText.setObjectName("ipText")
        self.resruleLabel = QtWidgets.QLabel(self.responseFrame)
        self.resruleLabel.setGeometry(QtCore.QRect(480, 60, 91, 21))
        self.resruleLabel.setObjectName("resruleLabel")
        self.resruleSelect = QtWidgets.QComboBox(self.responseFrame)
        self.resruleSelect.setGeometry(QtCore.QRect(520, 60, 79, 22))
        self.resruleSelect.setObjectName("resruleSelect")
        self.resruleSelect.addItem("")
        self.resruleSelect.addItem("")
        self.resruleButton = QtWidgets.QPushButton(self.responseFrame)
        self.resruleButton.setGeometry(QtCore.QRect(670, 60, 80, 31))
        self.resruleButton.setObjectName("resruleButton")
        self.ruleFrame = QtWidgets.QFrame(self.centralWidget)
        self.ruleFrame.setGeometry(QtCore.QRect(10, 340, 781, 241))
        self.ruleFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ruleFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ruleFrame.setObjectName("ruleFrame")
        self.ruleTitle = QtWidgets.QLabel(self.ruleFrame)
        self.ruleTitle.setGeometry(QtCore.QRect(20, 10, 91, 21))
        self.ruleTitle.setObjectName("ruleTitle")
        self.removeButton = QtWidgets.QPushButton(self.ruleFrame)
        self.removeButton.setGeometry(QtCore.QRect(670, 200, 80, 31))
        self.removeButton.setObjectName("removeButton")
        self.ruleTable = QtWidgets.QTableWidget(self.ruleFrame)
        self.ruleTable.setGeometry(QtCore.QRect(20, 40, 620, 191))
        self.ruleTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.ruleTable.setObjectName("ruleTable")
        self.ruleTable.setColumnCount(0)
        self.ruleTable.setRowCount(0)
        self.ruleTable.horizontalHeader().setVisible(True)
        self.ruleTable.horizontalHeader().setCascadingSectionResizes(False)
        self.proxyTitle = QtWidgets.QLabel(self.centralWidget)
        self.proxyTitle.setGeometry(QtCore.QRect(320, 30, 161, 16))
        self.proxyTitle.setObjectName("proxyTitle")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.methodSelect.setItemText(0, _translate("MainWindow", "GET"))
        self.methodSelect.setItemText(1, _translate("MainWindow", "POST"))
        self.methodSelect.setItemText(2, _translate("MainWindow", "PUT"))
        self.methodSelect.setItemText(3, _translate("MainWindow", "DELETE"))
        self.methodSelect.setItemText(4, _translate("MainWindow", "HEAD"))
        self.reqruleSelect.setItemText(0, _translate("MainWindow", "ALLOW"))
        self.reqruleSelect.setItemText(1, _translate("MainWindow", "DENY"))
        self.reqruleButton.setText(_translate("MainWindow", "ADD"))
        self.requestTitle.setText(_translate("MainWindow", "请求规则添加"))
        self.methodLabel.setText(_translate("MainWindow", "Method:"))
        self.urlLabel.setText(_translate("MainWindow", "Url:"))
        self.reqruleLable.setText(_translate("MainWindow", "Rule:"))
        self.responseTitle.setText(_translate("MainWindow", "响应规则添加"))
        self.typeLabel.setText(_translate("MainWindow", "Type:"))
        self.typeSelect.setItemText(0, _translate("MainWindow", "APPLET"))
        self.typeSelect.setItemText(1, _translate("MainWindow", "DOC"))
        self.typeSelect.setItemText(2, _translate("MainWindow", "APK"))
        self.ipLabel.setText(_translate("MainWindow", "Url:"))
        self.resruleLabel.setText(_translate("MainWindow", "Rule:"))
        self.resruleSelect.setItemText(0, _translate("MainWindow", "ALLOW"))
        self.resruleSelect.setItemText(1, _translate("MainWindow", "DENY"))
        self.resruleButton.setText(_translate("MainWindow", "ADD"))
        self.ruleTitle.setText(_translate("MainWindow", "目前规则"))
        self.removeButton.setText(_translate("MainWindow", "REMOVE"))
        self.proxyTitle.setText(_translate("MainWindow", "透明代理防火墙用户界面"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

